language: java
sudo: required
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean test
notifications:
  slack:
    secure: Ueku2w/RdSfh1zEDErTbHi+hRx154fH10ykGcfrXPXhTVtWopG73BGDRKfVgU1MCokEo+2jtkRAuJB29R1PV8E3845wWJFs9ZPGcl0rjfx3qP2G/bCuARRHmBJ33YStROvaVF3ppNjJau7VinIF3giem+4WgtQ8KPmqqviDg8Tw=
after_success:
  - mvn clean test jacoco:report coveralls:report 
